apiVersion: apps/v1
kind: Deployment
metadata:
  name: How-You-know-me
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: hi
  template:
    metadata:
      labels:
        app: hi
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: gutley
        ports:
        - containerPort: 80
